apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops-app
  type: NodePort  # Use LoadBalancer if on Cloud (AWS/GCP)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007 # Access via http://localhost:30007 (minikube ip)
